

export const AUTH_TOKEN                 = 'AUTH_TOKEN';
export const AUTH_FAILURE               = 'AUTH_FAILURE';
export const AUTH_LOGOUT                = 'AUTH_LOGOUT';
export const UPDATE_ADMIN_PASSWORD      = 'UPDATE_ADMIN_PASSWORD';
export const UPDATE_PASSWORD_FAILURE    = 'UPDATE_PASSWORD_FAILURE';
export const USER_DISCUSSION            = 'USER_DISCUSSION';
export const ADD_PATIENT                = 'ADD_PATIENT';
export const GET_PHYSICIAN_FAILURE      = 'GET_PHYSICIAN_FAILURE';
    
// export const ADD_PHARMACIST_PROFILE_DATA = 'ADD_PHARMACIST_PROFILE_DATA'
// export const FETCH_PHARMACIST_PROFILE_DATA = 'FETCH_PHARMACIST_PROFILE_DATA';
// export const PHARMACIST_TABEL_DATA = 'PHARMACIST_TABEL_DATA';
// export const PHARMACIST_UPDATE_PROFILE='PHARMACIST_UPDATE_PROFILE';
// export const PHARMACIST_INSTITUTION_LIST='PHARMACIST_INSTITUTION_LIST';
// export const PHARMACIST_COUNTRY_LIST='PHARMACIST_COUNTRY_LIST';
// export const PHARMACIST_INITIAL_TYPE_LIST='PHARMACIST_INITIAL_TYPE_LIST';

